import {
  Activity,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  CalendarCheck,
  CheckCircle,
  ChevronDown,
  Clock,
  DollarSign,
  Download,
  Edit3,
  Filter,
  LayoutDashboard,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  MoreHorizontal,
  Phone,
  Plus,
  PlusCircle,
  Receipt,
  Search,
  Settings,
  ShieldCheck,
  ThumbsUp,
  Trash2,
  Umbrella,
  UserCheck,
  UserPlus,
  Users,
  X,
} from 'lucide-react'

const icons = {
  activity: Activity,
  banknote: Banknote,
  'bar-chart-3': BarChart3,
  bell: Bell,
  'book-open': BookOpen,
  briefcase: Briefcase,
  building: Building,
  'building-2': Building2,
  'calendar-check': CalendarCheck,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  clock: Clock,
  'dollar-sign': DollarSign,
  download: Download,
  'edit-3': Edit3,
  filter: Filter,
  'layout-dashboard': LayoutDashboard,
  'log-out': LogOut,
  mail: Mail,
  menu: Menu,
  'message-square': MessageSquare,
  'more-horizontal': MoreHorizontal,
  phone: Phone,
  plus: Plus,
  'plus-circle': PlusCircle,
  receipt: Receipt,
  search: Search,
  settings: Settings,
  'shield-check': ShieldCheck,
  'thumbs-up': ThumbsUp,
  'trash-2': Trash2,
  umbrella: Umbrella,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  users: Users,
  x: X,
}

export default function Icon({ name, className = 'h-5 w-5', ...props }) {
  const LucideIcon = icons[name] ?? Activity
  return <LucideIcon className={className} strokeWidth={2} aria-hidden="true" {...props} />
}
